name: Docker Build, Trivy Scan, and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_scan_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t andonebekasi/myapp23:latest .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/

      - name: Run Trivy Scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL andonebekasi/myapp23:latest

      - name: Push to Docker Hub (If Scan Passed)
        if: success()
        run: |
          docker push andonebekasi/myapp23:latest
