name: Trivy Docker Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *' # Scan setiap hari jam 12:00 UTC

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myuser/myapp:latest'
          format: 'table'
          exit-code: '1' # Build gagal jika ada HIGH atau CRITICAL
          severity: 'HIGH,CRITICAL'
